[theme]
base="light"  # Ou "dark"

[server]
headless = true

[client]
showSidebarNavigation = false  # Enlève le menu en haut à gauche

[ui]
hideTopBar = true  # Cache la barre du haut (non officiel)

[global]
disableWatchdogWarning = true  # Désactive les avertissements